INSERT INTO companies (name, industry, org_type) VALUES
('BNY', 'Finance', 'Enterprise'),
('Protiviti', 'Consulting', 'Mid'),
('McKinsey', 'Finance', 'Enterprise'),
('Publicis Groupe', 'Tech', 'Enterprise'),
('BCG', 'Consulting', 'Enterprise'),
('FOX', 'Tech', 'Enterprise'),
('Experian', 'Tech', 'Enterprise'),
('PMG', 'Tech', 'Mid'),
('FTI Consulting', 'Consulting', 'Mid'),
('Bloomberg', 'Tech', 'Enterprise'),
('Microappdata', 'Tech', 'Startup'),
('Centurion Realty', 'Finance', 'Mid'),
('Mastercard', 'Tech', 'Enterprise'),
('AIG', 'Tech', 'Enterprise'),
('Warner Bros', 'Tech', 'Enterprise'),
('Dicks Sporting Goods', 'Tech', 'Enterprise'),
('Pfizer', 'Tech', 'Enterprise'),
('GEICO', 'Tech', 'Enterprise'),
('Oliver Wyman', 'Consulting', 'Enterprise'),
('Jane Street', 'Tech', 'Enterprise');



INSERT INTO applications (company_id, role_type, app_date, status, source, salary_expectation) VALUES
(1, 'Analyst Data Science', '2025-12-01', 'Applied', 'LinkedIn', 85000),
(2, 'Technology Consulting Consultant', '2025-12-02', 'Applied', 'LinkedIn', 90000),
(3, 'Business Analyst', '2025-12-03', 'Denied', 'LinkedIn', 95000),
(4, 'Data Scientist', '2025-12-05', 'Applied', 'LinkedIn', 100000),
(5, 'Full Time Associate', '2025-12-07', 'Denied', 'LinkedIn', 95000),
(6, 'Spring 2025 Data Analytics Internship', '2025-12-10', 'Applied', 'Handshake', 40000),
(7, 'Data Analytics Xcelator Program', '2025-12-12', 'Applied', 'LinkedIn', 85000),
(8, 'Graduate Leadership Program - Data Analytics Track', '2025-12-15', 'Denied', 'LinkedIn', 85000),
(9, 'Entry level Consultant Data Analytics', '2025-12-18', 'Denied', 'Handshake', 80000),
(10, 'Data Management Professional', '2025-10-30', 'Denied', 'Referral', 85000),
(11, 'Entry Level Business Analyst', '2025-12-20', 'Applied', 'LinkedIn', 75000),
(12, 'Financial Analyst', '2025-12-21', 'Applied', 'LinkedIn', 70000),
(13, 'Analytics Metrics 2026 Launch Program', '2025-12-22', 'Applied', 'LinkedIn', 85000),
(14, 'Actuarial Analyst', NULL, 'Denied', 'LinkedIn', 75000),
(15, 'Research Analytics Strategy Internships', NULL, 'Applied', 'LinkedIn', 45000),
(16, 'Technology Development Program - Data Science 2026', NULL, 'Applied', 'LinkedIn', 85000),
(17, 'Research and Development Rotational Program', NULL, 'Denied', 'LinkedIn', 80000),
(18, 'Process Analyst 1', NULL, 'Applied', 'LinkedIn', 70000),
(19, 'Entry Level Consultant', NULL, 'Denied', 'LinkedIn', 90000),
(20, 'Quantitative Researcher', NULL, 'Denied', 'LinkedIn', 120000);